include:
  - LibreChat/docker-compose.yml

networks:
  app-network:
    driver: bridge

services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - '9000:8080'
    networks:
      - app-network
    volumes:
      - ./stirling-data/tessdata:/usr/share/tessdata # OCR language files
      - ./stirling-data/configs:/configs # Settings & database
      - ./stirling-data/logs:/logs # Application logs
      - ./stirling-data/pipeline:/pipeline # Automation configs
    restart: unless-stopped
    environment:
      - LANGS=fr_FR
  excalidraw:
    image: excalidraw/excalidraw:latest
    ports:
      - "3001:80"
    networks:
      - app-network
    restart: unless-stopped
  trilium:
    image: triliumnext/trilium:latest
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - '8080:8080'
    networks:
      - app-network
    volumes:
      - ${TRILIUM_DATA_DIR:-~/trilium-data}:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
